name: Idiotic
url: http://idioticdev.com
author: Timothy Johnson
timezone: America/Los_Angeles
excerpt_separator: '#'
markdown: KramdownHtml5
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
exclude: [_exclude]
permalink: pretty
gems: [jekyll-coffeescript]
