name: Idiotic Design and Development
description: Living one mistake at a time.
url: http://idiotic-development.github.io/
timezone: America/Los_Angeles
markdown: kramdown
kramdown:
  input: GFM